# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: python:3.8
  cpu: 2
  memory: 4G

env:
  # Skip specific tasks by name. Set to a non-empty string to skip.
  SKIP_LINT_TASK: ""
  SKIP_TEST_TASK: ""
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"
  # Increment the build number to force new conda cache upload.
  CONDA_CACHE_BUILD: "0"
  # Increment the build number to force new nox cache upload.
  NOX_CACHE_BUILD: "0"
  # Increment the build number to force new pip cache upload.
  PIP_CACHE_BUILD: "0"
  # Pip package to be installed.
  PIP_CACHE_PACKAGES: "pip setuptools wheel nox pyyaml"
  # Conda packages to be installed.
  CONDA_CACHE_PACKAGES: "nox pip pyyaml"


#
# Linting
#
lint_task:
  only_if: ${SKIP_LINT_TASK} == ""
  auto_cancellation: true
  name: "${CIRRUS_OS}: flake8 and black"
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script:
      - echo "${CIRRUS_TASK_NAME} py${PYTHON_VERSION}"
      - echo "${PIP_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${PIP_CACHE_BUILD}"
  lint_script:
    - pip list
    - python -m pip install --retries 3 --upgrade ${PIP_CACHE_PACKAGES}
    - pip list
    - nox --session flake8
    - nox --session black


#
# Testing (Linux)
#
test_task:
  only_if: ${SKIP_TEST_TASK} == ""
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.6"
    env:
      PY_VER: "3.7"
    env:
      PY_VER: "3.8"
      COVERAGE: "true"
  name: "${CIRRUS_OS}: py${PY_VER} tests"
  container:
    image: gcc:latest
  env:
    PATH: ${HOME}/miniconda/bin:${PATH}
  conda_cache:
    folder: ${HOME}/miniconda
    fingerprint_script:
      - wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - echo "${CIRRUS_OS} $(sha256sum miniconda.sh)"
      - echo "${CONDA_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${CONDA_CACHE_BUILD}"
      - uname -r
    populate_script:
      - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
      - bash miniconda.sh -b -p ${HOME}/miniconda
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda update --quiet --name base conda
      - conda install --quiet --name base ${CONDA_CACHE_PACKAGES}
  nox_cache:
    folder: ${CIRRUS_WORKING_DIR}/.nox
    reupload_on_changes: true
    fingerprint_script:
      - echo "${CIRRUS_TASK_NAME}"
      - echo "${NOX_CACHE_BUILD}"
      - if [ -n "${IRIS_SOURCE}" ]; then echo "${IRIS_SOURCE}"; fi
  test_script:
    - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
    - nox --session tests -- --verbose
